### PR TITLE
Fixing nic error.

### PR DESCRIPTION
**Pull request by thpang**
Closes: #140 - Added dependency to fix nic issue.

### CODE REVIEW

**Comment by rdlaitila** [comment]
@iac-bot deploy

**Comment by rdlaitila** [comment]
@iac-bot deploy

**Comment by rdlaitila** [comment]
@thpang all deployments passed no nic errors observed during destroy phase.

**Comment by thpang** [comment]
I believe I'll add that into the next release which is going out tonight. Any objections @NormJohnIV This is a very minor update with dependencies and will help the automation side of things.

**Pull request merged**
