### PR TITLE
docs: (IAC-697): Updated the min_nodes value for compute node to 1

### PR DESCRIPTION
**Pull request by riragh**
# Changes:
Updated the `min_nodes` to 1 for `compute` node in variables.tf and CONFIG-VARS.md node_pool example.

# Tests:
With `min_nodes` set to 1 for `compute` node, verified the cluster was created with 1 compute node and 2 system nodes. After running the viya4-deployment all the pods initially started on `stateful` node, later `cas` node was created. After deployment stabilized logged in to SASStudio, compute context check was successful, SASStudio was usable.

### CODE REVIEW

**Review by jarpat — APPROVED** [review]

**Review by thpang — COMMENTED** [review]
Are we going to say anywhere in the README.md or the CONFIG-VARS.md file why we need at least 1 compute node? Folks will be asking and need to clarify somewhere here. Thanks.

**Comment by riragh** [comment]
> Are we going to say anywhere in the README.md or the CONFIG-VARS.md file why we need at least 1 compute node? Folks will be asking and need to clarify somewhere here. Thanks.

Good point, I'll reach out to you for details.

**Comment by thpang** [comment]
I think in the doc or sample file we should have in the `NOTE` section of the table or as a `NOTE` in the paragraph we just explain why compute needs 1 node. Very simple and clean.

**Comment by riragh** [comment]
> I think in the doc or sample file we should have in the `NOTE` section of the table or as a `NOTE` in the paragraph we just explain why compute needs 1 node. Very simple and clean.

Added the note in CONFIG-VARS.md file.

**Review by thpang — APPROVED** [review]

**Pull request merged**
