### PR TITLE
(IAC-503) Remove connect class references from iac-azure

### PR DESCRIPTION
**Pull request by riragh**
# Changes
Starting from 2021.2.6 the connect node pool is optional, removing it from the examples and defaults in variables.tf. 
sample-input-connect.tfvars was created to show the user how to create the node pool in case they are deploying on an older cadence.

# Tests

**Note**: The follow scenarios were run and produced the expected results, for more detail and the outputs please see the internal IAC-503 ticket.

- Use new IAC code, new install Viya 2021.2.6 and beyond: users use IAC/DAC default setting to deploy Viya 4, result in a successful deployment without "connect" node pool
- Use new IAC code, new install Viya 2021.2.6 and beyond: users are able to have a successful deployment with connect node pool (using the new sample-input-connect.tfvars)
- Use new IAC code (use the default settings), new install Viya 4 old cadences, e.g. 2021.2.4: This is a breaking change. This won’t work because connect pool is needed for 2021.2.5 and prior but defaults don’t have it. (Note: People can use old IAC code if they want to deploy 2021.2.5 and prior or see the next case).
- Use new IAC code (default settings), new install Viya 4 old cadences, e.g. 2021.2.5 (connect is needed for those cadences). Use the new example file sample-input-connect.tfvars and deploy 2021.2.5 will result in a successful deployment.
- Upgrade: Customer has Viya 2021.2.5 running and they complete a UIP to 2021.2.6. At this point, they have “connect”. The customer then updates their tfvars to remove reference to the connect node pool and asks Terraform to update the cluster. This results in a working Viya.

### CODE REVIEW

**Review by thpang — CHANGES_REQUESTED** [review]
The sample file name needs to change: sample-input-connect.tfvars or something to convey it's purpose and follow the current naming.

**Comment by riragh** [comment]
> The sample file name needs to change: sample-input-connect.tfvars or something to convey it's purpose and follow the current naming.

Updated the file name to sample-input-connect.tfvars

**Comment by thpang** [comment]
Why is this one in draft?

**Comment by riragh** [comment]
> Why is this one in draft?

I am still testing the change. Wanted Jay to verify the changes are same as his in GCP so created the PR. I'll push it to actual review after I complete testing all the scenarios.

**Comment by thpang** [comment]
Sounds good.

**Comment by riragh** [comment]
Testing complete (for details please see IAC-503), ready for review.

**Review by thpang — APPROVED** [review]
LGTM

**Review by jarpat — APPROVED** [review]

**Pull request merged**
