### PR TITLE
(IAC-533) New Readme for remove connect class

### PR DESCRIPTION
**Pull request by riragh**
New Readme document has been added for the remove connect class reference.

### CODE REVIEW

**Review by supear — CHANGES_REQUESTED** [review]
Typo in step 1 -- remove extra space here:  ... document]( https ...
When the update to 2021.2.6 has completed successfully, use ... section. [lowercase "use" and add period]

**Comment by riragh** [comment]
@supear I see you updated the requested changes in your commit. Could you remove the changes requested or mark complete somehow.

**Comment by riragh** [comment]
@supear I see you updated the requested changes in your commit. Could you remove the changes requested or mark complete somehow.

**Review by sayeun — APPROVED** [review]
The latest update by @supear looks good.

**Comment by supear** [comment]
Fixed upstream.

**Comment by riragh** [comment]
Need to get this changes merged, reopening PR

**Pull request merged**
