### PR TITLE
use subnet cidrs for nfs exports instead of first vnet cidr

### LINKED ISSUE #186: Incorrect base_cidr_block
When deploying in existing VNET and subnets, the script is picking up the wrong base CIDR block. As a result, the jump VM was unable to perform "mount -a" successfully.

The script assumes a single address space in the VNET, which might not necessarily be the case in an existing network.  In this case, the VNET consists of discontiguous address spaces:
10.27.0.0/15,10.33.1.0/24, 10.33.2.0/24, 10.33.3.0/24, 10.33.4.0/24, 10.33.5.0/24, 10.33.6.0/24, 172.27.0.0/15, etc.

Only 10.33.5.0/24 and 10.33.6.0/24 are used for the aks and misc subnets respectively.

The function in question is:
base_cidr_block = element(module.vnet.address_space, 0)

### PR DESCRIPTION
**Pull request by enderm**
Closes #186

### CODE REVIEW

**Comment by thpang** [comment]
Looks good. Will be handing this over to the test team for validation.

**Comment by thpang** [comment]
@jkmin96 has been made aware and it's in the test teams queue.

**Comment by jkmin96** [comment]
I verified the fix successfully.

**Review by jkmin96 — APPROVED** [review]
I verified the fix.
My deployment was successfully using existing vnet/subnets.

**Pull request merged**
